package switchCommands;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

/*
 * 	1) Launch new Browser
	2) Open URL “http://toolsqa.wpengine.com/automation-practice-switch-windows/”	
	3) Click on Button “Alert Box”, it will open a Pop Up Window generated by JavaScript	
	4) Switch to Alert window (Use ‘SwitchTo()Alert() command)	
	5) Close the Pop Up Window (Use Accept command)
 */

public class PracticeSwitchWindow {
	
	public static WebDriver driver;
	
	public static void main(String[] args) throws InterruptedException {

		// Create a new instance of the Chrome driver
		System.setProperty("webdriver.chrome.driver", "C:\\Program Files\\Java\\chrome\\chromedriver.exe");
		
		driver = new ChromeDriver();

		// Put an Implicit wait, this means that any search for elements on the
		// page could take the time the implicit wait is set for before throwing
		// exception
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

		// Launch the URL
		driver.get("http://toolsqa.wpengine.com/automation-practice-switch-windows/");

		// Click on the Button "Alert Box"
		driver.findElement(By.id("alert")).click();
		//driver.findElement(By.id("timingAlert")).click();
		
		 //driver.findElement(By.name("Alert Box")).click();

		// Switch to JavaScript Alert window
		Alert myAlert = driver.switchTo().alert();
		
		Thread.sleep(4000);
		
		// Accept the Alert
		myAlert.accept();
		
		
		Thread.sleep(4000);

		// Close Original window
		driver.close();

	}
}
